#!/usr/bin/env bash
# Bash to install and configure Haproxy on a load balancer

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*

if ! grep -q "backend web-backend" /etc/haproxy/haproxy.cfg; then
	cat >> /etc/haproxy/haproxy.cfg << EOF

backend web-backend
        balance roundrobin
        server 224883-web-01 52.91.146.125:80 check
        server 224883-web-02 54.165.149.76:80 check

frontend web-frontend
        bind *:80
        mode http
        default_backend web-backend
EOF
fi
service haproxy restart
