#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes

hrs=0
mins=1
while [ $hrs -ne 13 ]
do
	echo "Hour: $hrs"
	((hrs++))
	while [ $mins -ne 60 ]
	do
		echo $mins
		((mins++))
	done
	((mins = 1))
done
